# nixpacks.toml

# Specify the language and version
[language]
framework = "nextjs"
version = "18.x"     # Define your preferred Node.js version

# Specify build steps
[phases.setup]
nixpkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn run build"]

# Define start command
[phases.start]
cmds = ["yarn run start"]

# Port configuration
[variables]
PORT = "3000"
